### ISSUE TITLE
Differences with troff type system (gtroff, neatroff)

### ISSUE THREAD

**Issue by KaneRoot** [zhiayang/sap#1]
Hello,

I just saw your project and I wonder why you don't want to use `troff`.

`gtroff`and `neatroff` (and their companions like `tbl`, `grap`, etc.) are great applications to create documents. Is there a reason you don't use them? If so, this may be relevant in the README.

Thanks!

**Comment by zhiayang** [comment]
I am making this project partly because I want to, and not just because I want to make a pretty PDF. If that was my actual goal, I can easily scrape together a bunch of LaTeX (or `(g|t|gt|neat)roff`), make my PDF, and be on my way. In fact that is what I have been doing for the past 5 years.

As for troff specifically, I am not very familiar with it, but at this point I am not willing to invest time into another typesetting system and be forced into its ecosystem along with all its limitations. From the most cursory glance, troff's macro system/language is nowhere near as powerful as I want sap's to be, and this appears to be true for troff derivatives as well.
